// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQcmWAFW2_jEWDCJ42lyxSkPOb-TOuao',
    appId: '1:292823040139:android:5f8a84c166cb9ab001148e',
    messagingSenderId: '292823040139',
    projectId: 'votingapp-33fb8',
    storageBucket: 'votingapp-33fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsIZWCAzRCCu6admhfqCDoUI1BSpFPta0',
    appId: '1:292823040139:ios:c7a1ec307b85e29b01148e',
    messagingSenderId: '292823040139',
    projectId: 'votingapp-33fb8',
    storageBucket: 'votingapp-33fb8.appspot.com',
    iosClientId: '292823040139-ivjs6a0snju145o6r9v89qe60575gkb8.apps.googleusercontent.com',
    iosBundleId: 'com.voting.app',
  );
}
